version: '3'

services:
  backend:
    container_name: backend
    image: hseong3243/anifriends:backend
    ports:
      - "8080:8080"
    user: "1000:1000"
    networks:
      - anifriends
    volumes:
      - /home/ec2-user/logs:/logs

  redis:
    container_name: redis
    image: redis:latest
    depends_on:
      - backend
    ports:
      - "6379:6379"
    networks:
      - anifriends

networks:
  anifriends:
